[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "prehension"
version = "0.0.2"
authors = [
  { name="Anton R Sobinov", email="an.sobinov@gmail.com" }
]
description = "Tools for processing and extracting kinematic and kinetic data from prehension experiments."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",

    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: Microsoft :: Windows",
    "Environment :: Console",

    "Development Status :: 4 - Beta",
]
dependencies = [
    "numpy",
    'matplotlib',
    'scipy',
    'opencv-contrib-python',
    'pyyaml',
    'astropy',
    'tqdm',
    'ffmpegio',
    'pandas',  # to be dropped
    'timed_sparse_matrix',
    'reporting_pool',
    'pythonnet'
]

[tool.setuptools]
packages = [
    "prehension",
    "prehension_scripts"
]

[project.optional-dependencies]
# Jarvis should be installed from https://github.com/craman96/JARVIS-HybridNet
jarvis = [
    "joblib",
    ]
# ncams should be installed from https://github.com/CMGreenspon/NCams
ncams = [
]

[project.urls]
Homepage = "https://github.com/SobinovLab/prehension"
